[workspace]
resolver = "2"
members = [
    "chuck-core",
    "chuck-cli",
    "src-tauri",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
